data "aws_iam_policy_document" "restricted_admin" {
  statement {
    effect = "Allow"

    actions = [
      "acm:*",
      "apigateway:*",
      "athena:*",
      "automation:*",
      "autoscaling:*",
      "aws-marketplace:*",
      "batch:*",
      "cloudformation:*",
      "cloudtrail:*",
      "cloudwatch:*",
      "codebuild:*",
      "codecommit:*",
      "codepipeline:*",
      "cognito:*",
      "config:*",
      "datapipeline:*",
      "dlm:*",
      "dms:*",
      "dynamodb:*",
      "ec2:*",
      "ecr:*",
      "ecs:*",
      "elasticache:*",
      "elasticfilesystem:*",
      "elasticloadbalancing:*",
      "elasticmapreduce:*",
      "es:*",
      "events:*",
      "glacier:*",
      "glue:*",
      "guardduty:*",
      "health:*",
      "inspector:*",
      "kinesis:*",
      "kms:*",
      "lakeformation:*",
      "lambda:*",
      "logs:*",
      "ram:*",
      "redshift:*",
      "rds:*",
      "resource-groups:ListGroups*",
      "route53:*",
      "route53domains:*",
      "s3:*",
      "securityhub:Describe*",
      "securityhub:Get*",
      "securityhub:List*",
      "ses:*",
      "shield:*",
      "sns:*",
      "sqs:*",
      "ssm:*",
      "sts:*",
      "states:*",
      "swf:*",
      "support:*",
      "trustedadvisor:*",
      "waf:*",
      "waf-regional:*",
    ]

    resources = ["*"]
  }

  statement {
    effect = "Allow"

    actions = [
      "iam:AddRoleToInstanceProfile",
      "iam:AddUserToGroup",
      "iam:AttachGroupPolicy",
      "iam:AttachRolePolicy",
      "iam:CreateAccessKey",
      "iam:CreateGroup",
      "iam:CreateInstanceProfile",
      "iam:CreateLoginProfile",
      "iam:CreateOpenIDConnectProvider",
      "iam:CreatePolicy",
      "iam:CreatePolicyVersion",
      "iam:CreateRole",
      "iam:CreateSAMLProvider",
      "iam:CreateServiceLinkedRole",
      "iam:CreateUser",
      "iam:CreateVirtualMFADevice",
      "iam:DeactivateMFADevice",
      "iam:DeleteAccessKey",
      "iam:DeleteGroup",
      "iam:DeleteGroupPolicy",
      "iam:DeleteInstanceProfile",
      "iam:DeleteLoginProfile",
      "iam:DeletePolicy",
      "iam:DeleteRole",
      "iam:DeleteRolePolicy",
      "iam:DeleteSAMLProvider",
      "iam:DeleteOpenIDConnectProvider",
      "iam:DeletePolicyVersion",
      "iam:DeleteSSHPublicKey",
      "iam:DeleteUser",
      "iam:DeleteUserPolicy",
      "iam:DeleteVirtualMFADevice",
      "iam:DetachGroupPolicy",
      "iam:DetachRolePolicy",
      "iam:DetachUserPolicy",
      "iam:EnableMFADevice",
      "iam:GenerateCredentialReport",
      "iam:GenerateServiceLastAccessedDetails",
      "iam:Get*",
      "iam:List*",
      "iam:PassRole",
      "iam:PutGroupPolicy",
      "iam:PutRolePolicy",
      "iam:PutUserPolicy",
      "iam:RemoveRoleFromInstanceProfile",
      "iam:RemoveUserFromGroup",
      "iam:SimulatePrincipalPolicy",
      "iam:TagRole",
      "iam:UntagRole",
      "iam:UpdateAccessKey",
      "iam:UpdateAssumeRolePolicy",
      "iam:UpdateGroup",
      "iam:UpdateLoginProfile",
      "iam:UpdateOpenIDConnectProviderThumbprint",
      "iam:UpdateRole",
      "iam:UpdateRoleDescription",
      "iam:UploadSSHPublicKey",
    ]

    resources = ["*"]
  }
}
