# based on: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/.circleci/config.yml
version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.12.29
  working_directory: /tmp/workspace/terraform

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: Check if Terraform configurations are properly formatted
          command: terraform fmt -check -recursive

workflows:
  version: 2
  build:
    jobs:
      - validate
